import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import './analytics';
import { NewtTestRunner } from '@/newt-pkg';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      {/* This only needs to exist once on the top level component */}
      <NewtTestRunner allowedEnvironments={['dev', 'stg']} />
      <body className={inter.className}>{children}</body>
    </html>
  )
}
